import { defineConfig } from 'vitest/config';
import tsconfigPaths from 'vite-tsconfig-paths';
import { resolve } from 'path';
import process from 'process';

const isCI = !!process.env.CI;

export default defineConfig({
  plugins: [tsconfigPaths()],
  test: {
    environment: 'happy-dom',
    globals: true,
    pool: isCI ? 'forks' : 'threads',
    poolOptions: {
      forks: { singleFork: true },
      threads: { singleThread: true },
    },
    setupFiles: ['./tests/vitest.setup.ts'],
    include: ['tests/**/*.{test,unit.test,integration.test}.{js,ts}'],
    exclude: [
      // Schach9x9 tests with import path issues (need separate fix)
      'tests/schach9x9/ai/**',
      'tests/schach9x9/battleChess3D*.test.ts',
      'tests/schach9x9/battleAnimations.test.ts',
      'tests/schach9x9/boardRenderer*.test.ts',
      'tests/schach9x9/campaign*.test.ts',
      'tests/schach9x9/controller*.test.ts',
      'tests/schach9x9/coverage*.test.ts',
      'tests/schach9x9/crossMode*.test.ts',
      'tests/schach9x9/debug_hash*.test.ts',
      'tests/schach9x9/domHandler.test.ts',
      'tests/schach9x9/errorManager.test.ts',
      'tests/schach9x9/evalBar.test.ts',
      'tests/schach9x9/fullGame.test.ts',
      'tests/schach9x9/gameController.test.ts',
      'tests/schach9x9/gameFlow*.test.ts',
      'tests/schach9x9/hintGenerator*.test.ts',
      'tests/schach9x9/integration.test.ts',
      'tests/schach9x9/modes/**',
      'tests/schach9x9/move*.test.ts',
      'tests/schach9x9/notificationUI.test.ts',
      'tests/schach9x9/pgnGenerator.test.ts',
      'tests/schach9x9/pgn_crossMode.test.ts',
      'tests/schach9x9/postGameAnalysis.test.ts',
      'tests/schach9x9/proceduralGenerator.test.ts',
      'tests/schach9x9/property.test.ts',
      'tests/schach9x9/puzzle*.test.ts',
      'tests/schach9x9/repro_bug.test.ts',
      'tests/schach9x9/setupPhase.test.ts',
      'tests/schach9x9/shop*.test.ts',
      'tests/schach9x9/snapshots.test.ts',
      'tests/schach9x9/sound*.test.ts',
      'tests/schach9x9/statistics.test.ts',
      'tests/schach9x9/swarm*.test.ts',
      'tests/schach9x9/tutor*/**',
      'tests/schach9x9/tutorial*.test.ts',
      'tests/schach9x9/ui.advanced.test.ts',
      'tests/schach9x9/ui.touch.test.ts',
      'tests/schach9x9/ui/AnalysisUI.unit.test.ts',
      'tests/schach9x9/ui/BoardRenderer.test.ts',
      'tests/schach9x9/ui/DOMHandler_coverage.test.ts',
      'tests/schach9x9/ui/GameStatusUI.test.ts',
      'tests/schach9x9/ui/OverlayManager.test.ts',
      'tests/schach9x9/ui/PuzzleMenu.test.ts',
      'tests/schach9x9/ui/TutorUI.test.ts',
      'tests/schach9x9/ui/ui_orchestrator.test.ts',
      'tests/schach9x9/undo_redo_repro.test.ts',
      'tests/schach9x9/upgradeMode*.test.ts',
      'tests/schach9x9/verify_mission*.test.ts',
    ],
    testTimeout: 60000,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      reportsDirectory: './coverage',
      exclude: [
        'node_modules/**',
        'dist/**',
        'tests/**',
        'tests-e2e/**',
        '*.config.*',
        'scripts/**',
        'public/**',
      ],
      thresholds: {
        lines: 80,
        branches: 80,
        functions: 80,
        statements: 80,
      },
    },
    resolve: {
      conditions: ['import', 'module', 'browser', 'default'],
      extensions: ['.js', '.ts', '.json'],
      mainFields: ['module', 'main'],
    },
  },
  resolve: {
    extensions: ['.js', '.ts', '.json'],
    alias: {
      '@trischach': resolve(__dirname, './js/trischach'),
      '@trischach/*': resolve(__dirname, './js/trischach/*'),
      '@schach9x9': resolve(__dirname, './js/schach9x9'),
      '@schach9x9/*': resolve(__dirname, './js/schach9x9/*'),
      '@shared': resolve(__dirname, './js/shared'),
      '@shared/*': resolve(__dirname, './js/shared/*'),
    },
  },
});
